
[[buildpacks]]
  uri = "localhost:5000/composite:latest"
  version = "0.0.1"


[[order]]

[[order]]

  [[order.group]]
    id = "composite"
    version = "0.0.1"


# Base images used to create the builder
[build]
image = "ghcr.io/bitsoex/bitso-build:jammy"
[run]
[[run.images]]
image = "ghcr.io/bitsoex/bitso-runner:jammy"
