api = "0.10"
WithWindowsBuild = false
WithLinuxBuild = false

[buildpack]
  id = "composite"
  version = "0.0.1"


[[order]]

    [[order.group]]
    id = "not-much"
    version = "0.0.1"
    optional = true

    [[order.group]]
    id = "curl"
    version = "0.0.1"